Repository trace4cats/trace4cats-sttp, pull requests merged in 2021-07, with the labels that each got.

#10 Update cats, http4s-backend to 3.3.9
  project/Dependencies.scala
Labels: dependency-update

#14 Update Mergify rules
  .github/mergify.yml
Labels: skip-changelog

#17 Change `ToHeaders` implementation
  modules/sttp-client3/src/main/scala/io/janstenpickle/trace4cats/sttp/client3/SttpBackendSyntax.scala
  modules/sttp-client3/src/test/scala/io/janstenpickle/trace4cats/sttp/client3/TracedSttpBackendCtxSpec.scala
Labels: enhancement

#18 Update sbt-ci-release-early to 2.0.17
  project/plugins.sbt
Labels: dependency-update

#19 Update sbt-scalafmt to 2.4.3
  project/plugins.sbt
Labels: dependency-update

#20 Update tapir-cats, tapir-json-circe to 0.18.0
  project/Dependencies.scala
Labels: dependency-update

#21 Update sbt to 1.5.5
  project/build.properties
Labels: dependency-update

#22 Update cats, http4s-backend to 3.3.11
  project/Dependencies.scala
Labels: dependency-update

#23 Update model:core to 1.4.9
  project/Dependencies.scala
Labels: dependency-update

#24 Update tapir to 0.19.0-M1
  build.sbt
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/BaseServerEndpointTracerSpec.scala
  project/Dependencies.scala
Labels: dependency-update

#25 Update logback-classic to 1.2.4
  project/Dependencies.scala
Labels: dependency-update

#26 Update tapir-cats, tapir-http4s-server, ... to 0.19.0-M2
  project/Dependencies.scala
Labels: dependency-update

#27 Update logback-classic to 1.2.5
  project/Dependencies.scala
Labels: dependency-update

#30 Update cats, http4s-backend to 3.3.12
  project/Dependencies.scala
Labels: dependency-update

#29 Add Scala 3 build
  .github/workflows/ci.yml
  ci-release.sbt
  modules/sttp-client3/src/test/scala/io/janstenpickle/trace4cats/sttp/client3/Instances.scala
  modules/sttp-client3/src/test/scala/io/janstenpickle/trace4cats/sttp/client3/TracedSttpBackendCtxSpec.scala
  modules/sttp-client3/src/test/scala/io/janstenpickle/trace4cats/sttp/client3/TracedSttpBackendSpec.scala
  modules/sttp-common/src/test/scala/io/janstenpickle/trace4cats/sttp/common/CommonInstances.scala
  modules/sttp-common/src/test/scala/io/janstenpickle/trace4cats/sttp/common/RunIOToId.scala
  modules/sttp-common/src/test/scala/io/janstenpickle/trace4cats/sttp/common/SttpHeadersConverterSpec.scala
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/Instances.scala
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/TracedServerEndpointCtxSpec.scala
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/TracedServerEndpointSpec.scala
  modules/sttp-tapir/src/test/scala/io/janstenpickle/trace4cats/sttp/tapir/model/ErrorInfo.scala
  project/Dependencies.scala
Labels: enhancement
